FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build

RUN go get -u github.com/DaniilDenisyuk/design-practice-2/build/cmd/bood

WORKDIR /go/src/practice-3
COPY . .

RUN rm -f build.bood && mv integration.bood build.bood
# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
ENTRYPOINT ["bood"]